### PR TITLE
cadc-9749 Added support for multiple OIDC.

### PR DESCRIPTION
**Pull request by yeunga**
- updated OIDCUtil.getRelyParty(...) to read oidc and corresponding secret from a config file.
- added a sample ac-oidc-clients.properties file.

### CODE REVIEW

**Review by brianmajor — CHANGES_REQUESTED** [review]
Could you please add a unit test for the getRelyParty() method?  Then we'll at least have a sample properties files in the opensource code.  The test can be very simple.

**Comment by yeunga** [comment]
> Could you please add a unit test for the getRelyParty() method? Then we'll at least have a sample properties files in the opensource code. The test can be very simple.

Sure. However I have already included a sample properties file.
BTW, the current code does not handle the case when there is no value in the KVP, e.g. 'oidc='. I can add a check for this scenario and throw a RuntimeException.

**Comment by brianmajor** [comment]
Oh, maybe you forgot to add the sample properties file?  I don't think I
saw it in the 'files changed' view.
Don't worry about the missing value case

**Comment by yeunga** [comment]
> Oh, maybe you forgot to add the sample properties file? I don't think I saw it in the 'files changed' view. Don't worry about the missing value case
> […](#)
If expand the first link above on commits, the first file is the ac-oidc-clients.properties.

**Review by brianmajor — APPROVED** [review]

**Pull request merged**
